development:
  adapter: sqlite
  database:
  max_connections: 5
  pool_timeout: 5000

production:
  adapter: sqlite
  database:
  max_connections: 5
  pool_timeout: 5000

test: &test
  adapter: sqlite
  database:
  max_connections: 5
  pool_timeout: 5000
